import { ID_TYPES, isEqpCodePrefix, type CandidateAnnotation, type IdType } from "../domain";

/** User-controlled fields required to turn an exact source span into a candidate. */
export interface ManualAnnotationInput {
  /** Stable candidate identifier generated by the caller. */
  id: string;
  /** Inclusive UTF-16 offset into the original report. */
  start: number;
  /** Exclusive UTF-16 offset into the original report. */
  end: number;
  /** Reviewer-selected semantic class used for display and feedback. */
  entityClass: string;
  /** One or more reviewer-selected identifier families. */
  idTypes: readonly IdType[];
  /** Required approved category when EQPCODE is among `idTypes`. */
  eqpPrefix?: string;
  /** Optional explanation copied to every recommendation on the annotation. */
  rationale?: string;
}

/**
 * Builds a validated exact-span annotation from an explicit user selection.
 *
 * @param report Unmodified source report used to recover the selected text.
 * @param input Offsets and reviewer choices collected by the manual form.
 * @returns A normalized manual annotation, or `null` when any invariant fails.
 */
export function createManualAnnotation(report: string, input: ManualAnnotationInput): CandidateAnnotation | null {
  // Reject fractional, reversed, negative, and out-of-bounds offsets before slicing.
  if (!Number.isInteger(input.start) || !Number.isInteger(input.end)) return null;
  if (input.start < 0 || input.end > report.length || input.start >= input.end) return null;
  const text = report.slice(input.start, input.end);
  if (!text.trim() || /_/.test(text)) return null;

  // Deduplicate valid families while retaining the user's original order.
  const knownTypes = new Set<IdType>(ID_TYPES);
  const idTypes = [...new Set(input.idTypes)].filter((type) => knownTypes.has(type));
  if (!idTypes.length || !input.entityClass.trim()) return null;
  if (idTypes.includes("EQPCODE") && !isEqpCodePrefix(input.eqpPrefix)) return null;

  const rationale = input.rationale?.trim() || "Added manually by the user after reviewing the report.";
  return {
    id: input.id,
    start: input.start,
    end: input.end,
    text,
    entityClass: input.entityClass.trim(),
    possibleIdTypes: idTypes.map((type) => ({
      type,
      confidence: 1,
      rationale,
      ...(type === "EQPCODE" ? { eqpPrefix: input.eqpPrefix } : {}),
    })),
    source: "manual",
  };
}
